version: "3.3"
services:
  backendApp:
    image: "flaskproto:latest"
    tty: true
    deploy:
      replicas: 1
    ports:
      - 8080:80
    volumes:
      - backendLogs:/var/log/apache2
  
volumes:
  backendLogs:
